FROM python:3.8.10

# Set the working directory in the container
WORKDIR /app

COPY ./utils/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r utils/requirements.txt

# Copy the data_management.py and .env files into the container
COPY api .
COPY .env .

ENV PORT 8080
EXPOSE 8080

# Run the api.py script
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]
