FROM python:3.8.10

# Set the working directory in the container
WORKDIR /app

# Copy the python dependency requirements file from utils folder into the containers working directory
COPY ./utils/requirements.txt utils/
RUN pip install --no-cache-dir -r ./utils/requirements.txt

# Copy the required files into the container
COPY . . 

# Run the machine learning model script
CMD ["python3", "modeling.py"]