version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: recommendation
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
      
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: data_management_app
    restart: unless-stopped
    volumes:
      - ./data:/app/data #TODO: check this
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: ["python", "data_management.py"]

volumes:
  db_data: