FROM python:3.8.10

WORKDIR /app

# Copy the python dependency requirements file from utils folder into the containers working directory
COPY ./utils/requirements.txt utils/
RUN pip install --no-cache-dir -r ./utils/requirements.txt

ENV MYSQL_ROOT_PASSWORD=admin1234
ENV MYSQL_DATABASE=recommendation

#RUN mysqldump -u admin -p recommendation > data.sql

# Copy the SQL dump file to /docker-entrypoint-initdb.d
COPY data.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
