# Configurations for the Content Based Recommendation System

model:
  content_features:
    - title
    - genres
    - cast
    - directors
    - synopsis
    - rating

  drop_columns:
    - ["duration"]
    - ["duration_min"]

  processed_features:
      - genres
      - cast
      - directors

  max_features: 5000
  stop_words: 'english'


recommendation:
  top_n: 5