# Configurations for the Content Based Recommendation System

data:
  movies_file: movies.csv

model:
  content_features:
    - title
    - genres
    - cast
    - directors
    - synopsis
    - rating

  drop_columns:
    - ["duration"]
    - ["duration_min"]

  processed_features:
      - genres
      - cast
      - directors

  max_features: 5000
  stop_words: 'english'


  collaborative_filtering:
    matrix_factorization: svd

recommendation:
  top_n: 5