FROM python:3.10

WORKDIR /app

ADD requirements.txt app/requirements.txt
CMD pip3 install -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
