name: Continuous Integration
on:
  push:
    branches:
      - feat-aida

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout on feat-aida
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"

      - name: Install Dependencies
        run: |
          pip install -r utils/requirements.txt

      - name: Run data_management_test.py
        run: pytest -vv data_management_test.py

      - name: Run api_test.py
        run: pytest -vv api_test.py

      - name: Run preprocessing_test.py
        run: pytest -vv preprocessing_test.py

      - name: Run webscraping_test.py
        run: pytest -vv webscraping_test.py

      - name: Run modeling_test.py
        run: pytest -vv modeling_test.py
