name: Continuous Integration
on:
  push:
    branches:
      - feat-aida

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout on feat-aida
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install -r utils/requirements.txt

      - name: Run Unit Tests
        run: pytest